### ISSUE TITLE
Is backend code open-source?

### ISSUE THREAD

**Issue by pradyunsg** [AnandChowdhary/rhythmsaga-api#2]
Hi!

Just wanted to ask if the backend code (http://rhythmsa.ga/api.php, http://rhythmsa.ga/api/*.php, http://sagamusic.herokuapp.com/*.php) is publicly available?
If not, is there any we I can get my hands on them? :innocent: 

offtopic: Any chance that you rework the UI of http://rhythmsa.ga/2?

**Comment by AnandChowdhary** [comment]
Hey!

No, the backend code is not publicly yet, since RhythmSaga is still in beta. Once we're all ready and finished, it'll be uploaded in this very repo.

http://rhythmsa.ga/2 is just a testing page for our second version API; we only use to see if certain things are in place working or not. We have no intentions of reworking the UI at this moment.

PS: If you can't wait for us to release the RhythmSaga code, you can totally get your hands on it by becoming a contributor to the API. *hint hint*

**Comment by pradyunsg** [comment]
Ok... How do I contribute to the API/become a contributor? :innocent:

PS: I do have nice (some big) ideas but I don't really know how feasible they are or how/where to propose them...

**Comment by AnandChowdhary** [comment]
Hit me up at anandchowdhary@gmail.com! Let's make it work.

**Comment by pradyunsg** [comment]
Well, that mail hasn't been sent yet... I'll finish up that mail next week once my exams are over and I have more time.

The suggestions were mainly on improving the API. (as one would expect)

(PS: I wrote this comment in 2 minutes. Apologies if I was terse...)

**Comment by pradyunsg** [comment]
Any Updates?

**Comment by pradyunsg** [comment]
Cleaning up my personal issues list - closing this.
